apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn
  namespace: nomados
  labels:
    app.kubernetes.io/name: coturn
    app.kubernetes.io/part-of: nomados-platform
    app.kubernetes.io/component: turn
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: coturn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coturn
    spec:
      containers:
        - name: coturn
          image: coturn/coturn:latest
          args:
            - -c
            - /etc/turnserver.conf
          ports:
            - containerPort: 3478
              protocol: TCP
              name: turn-tcp
            - containerPort: 3478
              protocol: UDP
              name: turn-udp
            - containerPort: 5349
              protocol: TCP
              name: turns-tcp
          volumeMounts:
            - name: turn-config
              mountPath: /etc/turnserver.conf
              subPath: turnserver.conf
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: turn-config
          configMap:
            name: coturn-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
  namespace: nomados
  labels:
    app.kubernetes.io/name: coturn
    app.kubernetes.io/part-of: nomados-platform
data:
  turnserver.conf: |
    listening-port=3478
    tls-listening-port=5349
    realm=nomados.dev
    server-name=nomados-turn
    lt-cred-mech
    fingerprint
    no-multicast-peers
    no-cli
    log-file=stdout
    verbose
---
apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: nomados
  labels:
    app.kubernetes.io/name: coturn
    app.kubernetes.io/part-of: nomados-platform
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: coturn
  ports:
    - port: 3478
      targetPort: 3478
      protocol: TCP
      name: turn-tcp
    - port: 3478
      targetPort: 3478
      protocol: UDP
      name: turn-udp
    - port: 5349
      targetPort: 5349
      protocol: TCP
      name: turns-tcp