#!/usr/bin/env bash
# generate-secrets.sh — Generate random secrets for NomadOS infrastructure
# Writes to infrastructure/docker/.env (used by docker-compose.yml)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$(dirname "$SCRIPT_DIR")/docker/.env"

generate_secret() {
  openssl rand -hex 32
}

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo "Found existing .env at $ENV_FILE"
  read -rp "Overwrite? [y/N] " confirm
  if [[ ! "$confirm" =~ ^[yY]$ ]]; then
    echo "Aborted. Existing .env kept."
    exit 0
  fi
fi

SIGNING_SECRET=$(generate_secret)
MINIO_ROOT_PASSWORD=$(generate_secret)
MINIO_SECRET_KEY=$(generate_secret)
TURN_PASSWORD=$(generate_secret)
DATABASE_PASSWORD=$(generate_secret)

cat > "$ENV_FILE" <<EOF
# NomadOS secrets — generated by generate-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file. It is ignored by .gitignore.

SIGNING_SECRET=${SIGNING_SECRET}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
TURN_PASSWORD=${TURN_PASSWORD}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
EOF

echo "Secrets written to $ENV_FILE"
echo "  SIGNING_SECRET      = ${SIGNING_SECRET:0:8}..."
echo "  MINIO_ROOT_PASSWORD = ${MINIO_ROOT_PASSWORD:0:8}..."
echo "  MINIO_SECRET_KEY    = ${MINIO_SECRET_KEY:0:8}..."
echo "  TURN_PASSWORD       = ${TURN_PASSWORD:0:8}..."
echo "  DATABASE_PASSWORD   = ${DATABASE_PASSWORD:0:8}..."